### ISSUE TITLE
Does Go BLE support Mac El Captain?

### ISSUE THREAD

**Issue by jeffprestes** [currantlabs/ble#10]
Hello,

Does Go BLE support Mac El Captain? I am looking for something similar to Bleno but using Go.

Thanks

**Comment by roylee17** [comment]
Yes, it does. We leverage @raff' work for the OS X port. Checkout the
examples. They should work with both Linux and OS X.  The API are still
being tweaked every now and then. But we'll make sure the examples adapt
the changes and works.

**Comment by deadprogram** [comment]
I can confirm that the current master branch scanner and explorer examples work in El Capitan. This issue can probably be closed now.
