### ISSUE TITLE
can't find examples/lib/gatt

### ISSUE THREAD

**Issue by thasd3bu9** [currantlabs/ble#15]
Could you give me a hint?

thx

**Comment by roylee17** [comment]
examples/lib/gatt has graduated, and moved to /gatt.go :)
Rebase to a more recent commit should help.

**Comment by roylee17** [comment]
When we make some API changes, we'll also sync up the sample programs under /examples/.

**Comment by thasd3bu9** [comment]
Nice ;) thank you
