### ISSUE TITLE
Unhandled event & Failed to set MTU, err: Not implemented OS X Sierra

### ISSUE THREAD

**Issue by juliancheal** [currantlabs/ble#16]
Hey fellow BLE Golangers,

I've noticed this error in trying to connect to a BLE light. Although the device I'm connecting to I don't think is related.

I'm on OS X Sierra:
```
uname -a
Darwin Geomon 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

With Go version:
```
go version
go version go1.7.3 darwin/amd64
```

The error is:

```
2016/11/16 17:03:31 Unhandled event: xpc.Dict{"kCBMsgId":53, "kCBMsgArgs":xpc.Dict{"kCBMsgArgDeviceUUID":xpc.UUID{0x97, 0x99, 0xe, 0x8, 0x6b, 0x9b, 0x4b, 0xc, 0x90, 0xb0, 0x7f, 0x86, 0x11, 0x3f, 0x30, 0x7f}, "kCBMsgArgATTMTU":23}}

Connected Peripheral ID:97990e086b9b4b0c90b07f86113f307f, NAME:()
Failed to set MTU, err: Not implemented
2016/11/16 17:03:31 Unhandled event: xpc.Dict{"kCBMsgId":81, "kCBMsgArgs":xpc.Dict{"kCBMsgArgSupervisionTimeout":500, "kCBMsgArgDeviceUUID":xpc.UUID{0x97, 0x99, 0xe, 0x8, 0x6b, 0x9b, 0x4b, 0xc, 0x90, 0xb0, 0x7f, 0x86, 0x11, 0x3f, 0x30, 0x7f}, "kCBMsgArgConnectionInterval":198, "kCBMsgArgConnectionLatency":0}}
```

The MTU error I guess is related to https://github.com/currantlabs/ble/issues/3
But I am unsure of the `XPC.Dict` errors.

I am using both `currantlabs/ble` & `currantlabs/gatt`. However I am unsure where which of these the error is coming from.

If it's from `currantlabs/gatt` I can't add an issue at it's a fork of `PayPal/gatt`. And that project hasn't been touched it seems in a long while.

**Comment by deadprogram** [comment]
Hi @juliancheal that error is coming from gatt. I know because it is the same error as reported in https://github.com/hybridgroup/gobot/issues/348

**Comment by deadprogram** [comment]
Confirm that the latest currantlabs ble works on El Capitan without those errors.

**Comment by deadprogram** [comment]
Hi @juliancheal if you are using Gobot check out the https://github.com/hybridgroup/gobot/tree/feature/currantlabs-ble branch which uses this package now, and addresses the OSX issues.

If you are using ble package directly, ble for sure works on El Capitan.

In either case, probably this issue can be closed.
