### ISSUE TITLE
ClientOptions and connParams

### ISSUE THREAD

**Issue by helljai** [currantlabs/ble#18]
I cant quite work out if the code is complete to the point that i can make changes to the connection Paramters via ClientOptions, i'm looking to be able to change the slave latency after peripheral connection, but if its possible to just change it generally via device options rather than altering the defaults, that would be great, as i need to be able to set it on a per peripheral basis. Is this possible with current code base?

Edit: This is on linux, running as a central device

**Comment by roylee17** [comment]
@helljai, sorry for the late response.

Yes but you'll need to explicitly cast it to a HCI device.

Check the `updateLinuxParam` in the **blesh** example, and see if that's what you're looking for.

https://github.com/currantlabs/ble/blob/master/examples/blesh/main.go#L169

**Comment by roylee17** [comment]
@helljai I'm closing this. Let me know if you still have problem with this.
