### ISSUE TITLE
Error on Linux while init'ing HCI

### ISSUE THREAD

**Issue by syoder** [currantlabs/ble#19]
Here's a portion of the stacktrace:
```
panic: makechan: size out of range

goroutine 1 [running]:
panic(0x53e380, 0xc42000b1d0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/currantlabs/ble/linux/hci.NewPool(0x5, 0xffffffffffffffff, 0xc420039de8)
	/Users/syoder/src/golang/src/github.com/currantlabs/ble/linux/hci/buffer.go:19 +0x3e
github.com/currantlabs/ble/linux/hci.(*HCI).Init(0xc420096000, 0x0, 0x0)
	/Users/syoder/src/golang/src/github.com/currantlabs/ble/linux/hci/hci.go:152 +0x754
github.com/currantlabs/ble/linux.NewDevice(0x7fc022118080, 0xc420018db0, 0x56a0b2)
	/Users/syoder/src/golang/src/github.com/currantlabs/ble/linux/device.go:21 +0xac
...
```

Looks like it's trying to create a pool of buffers here: https://github.com/currantlabs/ble/blob/master/linux/hci/hci.go#L151

But `bufCnt` is zero, so it's trying to create a pool with -1 buffers, which crashes.

And here's the twist: it only crashes when I'm NOT running `hcidump`.  When I am running it, `bufCnt` has a proper value (15).  Maybe there's a race condition, and `hcidump` changes the timing?

If we can get to the bottom of this, I have a couple of PR's I'd like to submit that will add the ability to advertise arbitrary manufacturer and service advertisements (to allow altBeacon and Eddystone advertisements) on both mac and linux.

**Comment by syoder** [comment]
As far as I can tell, something in here is failing: https://github.com/currantlabs/ble/blob/master/linux/hci/hci.go#L187-L198

**Comment by syoder** [comment]
I've discovered that after the socket is bound, there is sometimes data to be read on the socket.  This is throwing everything off because the code doesn't expect anything yet.  When it does start sending commands, it gets confused because the response isn't what it was expecting.

After the socket is bound (https://github.com/currantlabs/ble/blob/master/linux/hci/socket/socket.go#L107) if I add some code to sleep for 50ms and then read from the socket to clear it out, then it works flawlessly.  I can submit a PR with this, but I'm still a little unsure if it's just an issue with my particular hardware or what.  It may be that after an "hci down" and "hci up", something gets written to the socket when the bluetooth hardware comes back up, which may explain the time delay issue.

Any thoughts?

**Comment by hasty** [comment]
Let me try it out on some of our hardware here; we haven't seen that issue, but doesn't seem like this would hurt aside from the (very slight) delay.

**Comment by syoder** [comment]
Yeah, it may be something very specific to my hardware.  I'm testing this with ubuntu running in VirtualBox on macOS, with a USB bluetooth dongle (you can't get a VM to attach to a Mac's builtin bluetooth).  It may be something with the dongle I'm using.  I've previously had good success with running bluetooth stuff in linux with this setup though.
