### ISSUE TITLE
Goroutine leak on Device disconnect

### ISSUE THREAD

**Issue by moogle19** [currantlabs/ble#24]
Hi,
when connecting and disconnecting from the Example-Server there is one Goroutine leak per connection. It is caused by `server.close()` in linux/att/server.go.
It sends a `false` on the unbuffered `server.chConfirm` channel which is never read.

Proposed fix:
Close the channel instead of sending a `false` and check the channel status in `indicate` instead of the value on the channel.

```diff
diff --git a/linux/att/server.go b/linux/att/server.go
index 3d360eb..6ff454a 100644
--- a/linux/att/server.go
+++ b/linux/att/server.go
@@ -104,7 +104,7 @@ func (s *Server) indicate(h uint16, data []byte) (int, error) {
 		return n, err
 	}
 	select {
-	case ok := <-s.chConfirm:
+	case _, ok := <-s.chConfirm:
 		if !ok {
 			return 0, io.ErrClosedPipe
 		}
@@ -169,7 +169,7 @@ func (s *Server) Loop() {
 }
 
 func (s *Server) close() error {
-	s.chConfirm <- false
+	close(s.chConfirm)
 	return s.conn.Close()
 }
 ```

**Comment by roylee17** [comment]
Good catch!

In that case, we might even want to prevent that close() being called more than once.
How about appending another commit that eliminates that function altogether, and handle it directly in  https://github.com/currantlabs/ble/blob/master/linux/att/server.go#L134

Thanks a lot.
