### ISSUE TITLE
WriteCharacteristic on Linux Doesn't Appear To Write

### ISSUE THREAD

**Issue by jaredwolff** [currantlabs/ble#65]
I'm writing a configuration characteristic on the Nordic Thingy 52. So in order to do so, I've followed the example code in `blesh` to a tee. 

**Expected Behavior**

When I write this data blob to the characteristic in question, and read it back it should read `701760ea60eadc0503674e1d`

```
    data,_ := hex.DecodeString("701760ea60eadc0503674e1d")

    fmt.Printf("[ %s ] Intended config: %x %d\n", m.client.Address().String(), data, len(data))

    err := m.client.WriteCharacteristic(u.(*ble.Characteristic),data,true)
    if err != nil {
      return errors.Wrap(err, "can't write characteristic")
    }

    new, err := m.client.ReadCharacteristic(u.(*ble.Characteristic))
    if err != nil {
      return errors.Wrap(err, "can't read characteristic")
    }
    fmt.Printf("[ %s ] Config read: %x\n", m.client.Address().String(), new)
```

**Observed behavior**

When I read back the characteristic it displays the still default value of `60ea60ea60eadc0503674e1d`

Note: that this value can be changed with the phone app no problem.

**Comment by deadprogram** [comment]
Hello @jaredwolff I have been using both ReadCharacteristic and WriteCharacteristic successfully from Gobot on several devices using ble. 

Here is the code we use: https://github.com/hybridgroup/gobot/blob/master/platforms/ble/ble_client_adaptor.go#L129-L159

Looks pretty similar, are you sure your particular device does not require a response on the write operation?

**Comment by jaredwolff** [comment]
Hey Ron
Thanks for the reply. I’ll look into it more then.

**Comment by jaredwolff** [comment]
Looks like this may require a reply as it needs to request a RW authorization before writing. Thanks again.

**Comment by deadprogram** [comment]
:bowing_man:

**Comment by jaredwolff** [comment]
@deadprogram are there any workarounds for the WriteCharacteristic with a response? Right now that function looks like it does the same thing no matter what the bool value is.

**Comment by roylee17** [comment]
I'm wondering is it possible that it is the "payload" not accepted/valid by the target peripheral (nordic), so it didn't take effect. For example, it was expecting hex string, but got the raw bytes, or the other way around.

Do you have access to compare the difference of the payload between using an app and the BLE stack?

For example, log (print out) the payload on the target (nordic) device, or using a BLE sniffer to observe BLE packet in the air.

**Comment by deadprogram** [comment]
@jaredwolff on Linux with no response calls WriteCommand https://github.com/currantlabs/ble/blob/b53d98df90d415a1f018dc14b1df23aa1e56cefc/linux/gatt/client.go#L242 and with response calls Write https://github.com/currantlabs/ble/blob/b53d98df90d415a1f018dc14b1df23aa1e56cefc/linux/gatt/client.go#L244
